echo add nat46dev > /proc/net/nat46/control
ifconfig nat46dev up
ip route add 0.0.0.0/0 dev nat46dev

echo config nat46dev debug 255 >/proc/net/nat46/control
echo insert nat46dev local.v4 192.168.1.100/32 local.v6 2001:db8:1:1::1/128 local.style NONE remote.v4 8.8.8.8/32 remote.v6 2001:4860:4860::8888/128 remote.style NONE >/proc/net/nat46/control
echo insert nat46dev local.v4 192.168.1.101/32 local.v6 2001:db8:1:1::2/128 local.style NONE remote.v4 8.8.8.8/32 remote.v6 2001:4860:4860::8888/128 remote.style NONE >/proc/net/nat46/control

capture start nat46dev /mnt/host/test-harness/test-data/captured/basic.jsonl

# inject packets
inject /mnt/host/test-harness/tests/basic/inject-tap0.jsonl tap0

# remove the nat46 device
echo del nat46dev >/proc/net/nat46/control

capture stop all

echo nat46 packets:
cat /mnt/host/test-harness/test-data/captured/basic.jsonl

