#!/bin/sh
[ -z "$2" ] && echo "Error: should be run by odhcpc6c" && exit 1
 /lib/functions.sh
. /lib/netifd/netifd-proto.sh

log () {
  echo $1 $2 $3 $4 $5 $6 $7 $8 $9 >>/tmp/map.log
}

cmd () {
  log RUN: "$1 $2 $3 $4 $5 $6 $7 $8 $9"
  eval "$1 $2 $3 $4 $5 $6 $7 $8 $9"
}

log "DHCP"

case "$2" in
        bound)
                log STARTING "$1" 
                date >>/tmp/map.log
                cmd "insmod mapmint"                                                 
                ifconfig mapmint up promisc
                # sleep 2
                # /etc/init.d/firewall stop
                # iptables -t nat -F
                mdpc -w $1 -m 1100 | sed -e 's/ivictl/mapminctl/g' >>/tmp/map.log 2>>/tmp/map.log
                mdpc -w $1 -m 1100 | sed -e 's/ivictl/mapminctl/g' |  sed -e 's/-A POSTROUTING/-I zone_wan_postrouting/g' | sh | sh
                ip -4 route add default dev mapmint
                ip -6 route add 2001:db8:beef:1f00:c0:a8ff:6400:f00/128 dev mapmint
                ip -6 route add 2001:db8:feed::/64 via fe80::20c:29ff:fee3:4e11 dev eth1
                
        ;;
        unbound)
                log STOPPING "$1" 
                date >>/tmp/map.log
                # cmd "rmmod mapmint"
                # cmd "iptables -t nat -F"
        ;;
esac

